export enum TypeOTP {
  REGISTER = 'REGISTER',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  CHANGE_PHONE = 'CHANGE_PHONE',
}

export enum ProductStatusHistory {
  CREATE = 'CREATE',
  UPDATE_STOCK = 'UPDATE_STOCK',
  UPDATE_PRICE = 'UPDATE_PRICE',
  UPDATE_STOCK_PRICE = 'UPDATE_STOCK_PRICE',
  DELETE = 'DELETE',
}
